In [142]:
import pandas as pd
import numpy as np

df = pd.read_csv("country-data.csv")

In [143]:
df.head()

,country,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp
0,Afghanistan,90.2,10.0,7.58,44.9,1610,9.44,56.2,5.82,553
1,Albania,16.6,28.0,6.55,48.6,9930,4.49,76.3,1.65,4090
2,Algeria,27.3,38.4,4.17,31.4,12900,16.10,76.5,2.89,4460
3,Angola,119.0,62.3,2.85,42.9,5900,22.40,60.1,6.16,3530
4,Antigua and Barbuda,10.3,45.5,6.03,58.9,19100,1.44,76.8,2.13,12200

In [144]:
df.shape

(167, 10)

In [145]:
df.columns

Index(['country', 'child_mort', 'exports', 'health', 'imports', 'income',
       'inflation', 'life_expec', 'total_fer', 'gdpp'],
      dtype='str')

In [146]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     167 non-null    str
 1   child_mort  167 non-null    float64
 2   exports     167 non-null    float64
 3   health      167 non-null    float64
 4   imports     167 non-null    float64
 5   income      167 non-null    int64
 6   inflation   167 non-null    float64
 7   life_expec  167 non-null    float64
 8   total_fer   167 non-null    float64
 9   gdpp        167 non-null    int64
dtypes: float64(7), int64(2), str(1)
memory usage: 13.2 KB

In [147]:
df.isnull().sum()

country       0
child_mort    0
exports       0
health        0
imports       0
income        0
inflation     0
life_expec    0
total_fer     0
gdpp          0
dtype: int64

In [148]:
df.describe()

,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp
count,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000,167.000000
mean,38.270060,41.108976,6.815689,46.890215,17144.688623,7.781832,70.555689,2.947964,12964.155689
std,40.328931,27.412010,2.746837,24.209589,19278.067698,10.570704,8.893172,1.513848,18328.704809
min,2.600000,0.109000,1.810000,0.065900,609.000000,-4.210000,32.100000,1.150000,231.000000
25%,8.250000,23.800000,4.920000,30.200000,3355.000000,1.810000,65.300000,1.795000,1330.000000
50%,19.300000,35.000000,6.320000,43.300000,9960.000000,5.390000,73.100000,2.410000,4660.000000
75%,62.100000,51.350000,8.600000,58.750000,22800.000000,10.750000,76.800000,3.880000,14050.000000
max,208.000000,200.000000,17.900000,174.000000,125000.000000,104.000000,82.800000,7.490000,105000.000000

In [149]:
df["income"]

0       1610
1       9930
2      12900
3       5900
4      19100
       ...
162     2950
163    16500
164     4490
165     4480
166     3280
Name: income, Length: 167, dtype: int64

In [150]:
df[["country", "income", "gdpp"]]

                 country  income   gdpp
0            Afghanistan    1610    553
1                Albania    9930   4090
2                Algeria   12900   4460
3                 Angola    5900   3530
4    Antigua and Barbuda   19100  12200
..                   ...     ...    ...
162              Vanuatu    2950   2970
163            Venezuela   16500  13500
164              Vietnam    4490   1310
165                Yemen    4480   1310
166               Zambia    3280   1460

[167 rows x 3 columns]

10 countries with the highest child mortality

In [151]:
df.sort_values("child_mort", ascending=False).head(10)

,country,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp
66,Haiti,208.0,15.3,6.91,64.7,1500,5.45,32.1,3.33,662
132,Sierra Leone,160.0,16.8,13.10,34.5,1220,17.20,55.0,5.20,399
32,Chad,150.0,36.8,4.53,43.5,1930,6.39,56.5,6.59,897
31,Central African Republic,149.0,11.8,3.98,26.5,888,2.01,47.5,5.21,446
97,Mali,137.0,22.8,4.98,35.1,1870,4.37,59.5,6.55,708
113,Nigeria,130.0,25.3,5.07,17.4,5150,104.00,60.5,5.84,2330
112,Niger,123.0,22.2,5.16,49.1,814,2.55,58.8,7.49,348
3,Angola,119.0,62.3,2.85,42.9,5900,22.40,60.1,6.16,3530
25,Burkina Faso,116.0,19.2,6.74,29.6,1430,6.81,57.9,5.87,575
37,"Congo, Dem. Rep.",116.0,41.1,7.91,49.6,609,20.80,57.5,6.54,334

Correlation matrix

In [152]:
df.drop(columns="country").corr()

,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp
child_mort,1.000000,-0.318093,-0.200402,-0.127211,-0.524315,0.288276,-0.886676,0.848478,-0.483032
exports,-0.318093,1.000000,-0.114408,0.737381,0.516784,-0.107294,0.316313,-0.320011,0.418725
health,-0.200402,-0.114408,1.000000,0.095717,0.129579,-0.255376,0.210692,-0.196674,0.345966
imports,-0.127211,0.737381,0.095717,1.000000,0.122406,-0.246994,0.054391,-0.159048,0.115498
income,-0.524315,0.516784,0.129579,0.122406,1.000000,-0.147756,0.611962,-0.501840,0.895571
inflation,0.288276,-0.107294,-0.255376,-0.246994,-0.147756,1.000000,-0.239705,0.316921,-0.221631
life_expec,-0.886676,0.316313,0.210692,0.054391,0.611962,-0.239705,1.000000,-0.760875,0.600089
total_fer,0.848478,-0.320011,-0.196674,-0.159048,-0.501840,0.316921,-0.760875,1.000000,-0.454910
gdpp,-0.483032,0.418725,0.345966,0.115498,0.895571,-0.221631,0.600089,-0.454910,1.000000

5 countries with the highest and lowest gdpp

In [153]:
df.sort_values("gdpp", ascending=True).head(5)

,country,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp
26,Burundi,93.6,8.92,11.60,39.2,764,12.30,57.7,6.26,231
88,Liberia,89.3,19.10,11.80,92.6,700,5.47,60.8,5.02,327
37,"Congo, Dem. Rep.",116.0,41.10,7.91,49.6,609,20.80,57.5,6.54,334
112,Niger,123.0,22.20,5.16,49.1,814,2.55,58.8,7.49,348
132,Sierra Leone,160.0,16.80,13.10,34.5,1220,17.20,55.0,5.20,399

In [154]:
df.sort_values("gdpp", ascending=False).head(5)

,country,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp
91,Luxembourg,2.8,175.0,7.77,142.0,91700,3.620,81.3,1.63,105000
114,Norway,3.2,39.7,9.48,28.5,62300,5.950,81.0,1.95,87800
145,Switzerland,4.5,64.0,11.50,53.3,55500,0.317,82.2,1.52,74600
123,Qatar,9.0,62.3,1.81,23.8,125000,6.980,79.5,2.07,70300
44,Denmark,4.1,50.5,11.40,43.6,44000,3.220,79.5,1.87,58000

Principal Component Analysis

In [155]:
features = df.drop(columns="country")
X = features.to_numpy()
names = features.columns
countries = df["country"]

Standardization

In [156]:
mu = X.mean(axis=0)

In [157]:
sigma = X.std(axis=0, ddof=1)

In [158]:
X_scaled = (X - mu) / sigma

Covariance matrix

In [159]:
m = X_scaled.shape[0]
cov = (X_scaled.T @ X_scaled) / (m - 1)

In [160]:
np.allclose(cov, np.cov(X_scaled, rowvar=False))

True

In [161]:
vals, vecs = np.linalg.eigh(cov)

In [162]:
vals

array([0.06687501, 0.08831536, 0.11343874, 0.22358112, 0.66061903,
       0.99478456, 1.1703833 , 1.54634631, 4.13565658])

In [163]:
vecs

array([[-0.3275418 ,  0.68274306, -0.07948854, -0.20062815,  0.16896968,
        -0.37065326,  0.02954353,  0.19288394, -0.41951945],
       [ 0.12308207,  0.01419742, -0.70730269,  0.05933283, -0.05761584,
        -0.00309102, -0.14476069,  0.61316349,  0.28389698],
       [-0.11308797, -0.07249683, -0.24983051, -0.00727646, -0.51800037,
        -0.4618975 ,  0.59663237, -0.24308678,  0.15083782],
       [-0.09903717,  0.02894642,  0.59218953,  0.03003154, -0.25537642,
         0.07190746,  0.29992674,  0.67182064,  0.16148244],
       [-0.61298247, -0.35262369,  0.09556237, -0.16034699,  0.2471496 ,
        -0.39215904, -0.3015475 ,  0.02253553,  0.39844111],
       [ 0.02523614,  0.01153775,  0.10463252, -0.06628537, -0.7148691 ,
        -0.15044176, -0.64251951, -0.00840447, -0.19317293],
       [-0.29403981,  0.50466425,  0.01848639,  0.60112652, -0.1082198 ,
         0.20379723, -0.11391854, -0.22270674,  0.42583938],
       [ 0.02633585, -0.29335267,  0.02882643,  0.75068875,  0.13526221,
        -0.37830365, -0.01954925,  0.15523311, -0.40372896],
       [ 0.62564572,  0.24969636,  0.24299776, -0.01677876,  0.18016662,
        -0.53199457, -0.12297749, -0.0460224 ,  0.39264482]])

In [164]:
idx = np.argsort(vals)[::-1]

In [165]:
vecs = vecs[:, idx]

In [166]:
vals = vals[idx]

In [167]:
per = (vals / np.sum(vals)) * 100
per

array([45.95173979, 17.18162565, 13.0042589 , 11.05316181,  7.34021142,
        2.48423468,  1.2604304 ,  0.98128174,  0.74305562])

In [168]:
per_acc = np.cumsum(per)
per_acc

array([ 45.95173979,  63.13336544,  76.13762433,  87.19078614,
        94.53099756,  97.01523224,  98.27566264,  99.25694438,
       100.        ])

In [181]:
k = 5 # Number of eigenvectors that capture 94.5% of the info

In [170]:
D = vecs[:, :k]
pd.DataFrame(D, index=names, columns=[f"PC{i+1}" for i in range(k)])

                 PC1       PC2       PC3       PC4       PC5
child_mort -0.419519  0.192884  0.029544 -0.370653  0.168970
exports     0.283897  0.613163 -0.144761 -0.003091 -0.057616
health      0.150838 -0.243087  0.596632 -0.461897 -0.518000
imports     0.161482  0.671821  0.299927  0.071907 -0.255376
income      0.398441  0.022536 -0.301548 -0.392159  0.247150
inflation  -0.193173 -0.008404 -0.642520 -0.150442 -0.714869
life_expec  0.425839 -0.222707 -0.113919  0.203797 -0.108220
total_fer  -0.403729  0.155233 -0.019549 -0.378304  0.135262
gdpp        0.392645 -0.046022 -0.122977 -0.531995  0.180167

In [171]:
data1 = X_scaled[0]
data1

array([ 1.28765971, -1.13486665,  0.2782514 , -0.08220771, -0.80582187,
        0.15686445, -1.61423717,  1.89717646, -0.67714308])

In [172]:
data1_c = data1 @ D
data1_c

array([-2.90428986,  0.09533386,  0.71596521, -1.00224038,  0.15783535])

In [173]:
print(data1_c @ D.T)

[ 1.65609964 -0.87570337  0.34709041 -0.30258344 -0.93889103  0.13815452
 -1.56088894  1.57384865 -0.67116637]

In [174]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("pca", PCA(n_components=5))
])

C = pipe.fit_transform(X)
pca = pipe["pca"]

In [175]:
print(pca.explained_variance_ratio_.round(3))
print(pca.explained_variance_ratio_.cumsum().round(3))

[0.46  0.172 0.13  0.111 0.073]
[0.46  0.631 0.761 0.872 0.945]

In [176]:
cols = [f"PC{i+1}" for i in range(pca.n_components_)]
D_sk = pd.DataFrame(pca.components_.T, index=features.columns, columns=cols)
D_sk

                 PC1       PC2       PC3       PC4       PC5
child_mort -0.419519  0.192884 -0.029544  0.370653 -0.168970
exports     0.283897  0.613163  0.144761  0.003091  0.057616
health      0.150838 -0.243087 -0.596632  0.461897  0.518000
imports     0.161482  0.671821 -0.299927 -0.071907  0.255376
income      0.398441  0.022536  0.301548  0.392159 -0.247150
inflation  -0.193173 -0.008404  0.642520  0.150442  0.714869
life_expec  0.425839 -0.222707  0.113919 -0.203797  0.108220
total_fer  -0.403729  0.155233  0.019549  0.378304 -0.135262
gdpp        0.392645 -0.046022  0.122977  0.531995 -0.180167

In [177]:
C_df = pd.DataFrame(C, index=df["country"], columns=cols)

In [178]:
np.allclose(np.abs(D), np.abs(pca.components_.T))

True

In [179]:
D

array([[-0.41951945,  0.19288394,  0.02954353, -0.37065326,  0.16896968],
       [ 0.28389698,  0.61316349, -0.14476069, -0.00309102, -0.05761584],
       [ 0.15083782, -0.24308678,  0.59663237, -0.4618975 , -0.51800037],
       [ 0.16148244,  0.67182064,  0.29992674,  0.07190746, -0.25537642],
       [ 0.39844111,  0.02253553, -0.3015475 , -0.39215904,  0.2471496 ],
       [-0.19317293, -0.00840447, -0.64251951, -0.15044176, -0.7148691 ],
       [ 0.42583938, -0.22270674, -0.11391854,  0.20379723, -0.1082198 ],
       [-0.40372896,  0.15523311, -0.01954925, -0.37830365,  0.13526221],
       [ 0.39264482, -0.0460224 , -0.12297749, -0.53199457,  0.18016662]])

In [180]:
pca.components_.T

array([[-0.41951945,  0.19288394, -0.02954353,  0.37065326, -0.16896968],
       [ 0.28389698,  0.61316349,  0.14476069,  0.00309102,  0.05761584],
       [ 0.15083782, -0.24308678, -0.59663237,  0.4618975 ,  0.51800037],
       [ 0.16148244,  0.67182064, -0.29992674, -0.07190746,  0.25537642],
       [ 0.39844111,  0.02253553,  0.3015475 ,  0.39215904, -0.2471496 ],
       [-0.19317293, -0.00840447,  0.64251951,  0.15044176,  0.7148691 ],
       [ 0.42583938, -0.22270674,  0.11391854, -0.20379723,  0.1082198 ],
       [-0.40372896,  0.15523311,  0.01954925,  0.37830365, -0.13526221],
       [ 0.39264482, -0.0460224 ,  0.12297749,  0.53199457, -0.18016662]])